### ISSUE TITLE
Not compatible with : Plex Assistant

### ISSUE THREAD

**Issue by pergolafabio** [nagyrobi/home-assistant-custom-components-linkplay#48]
Guys, i installed this add-on yesterday, when i comment out the media_player config, no issues
whn i add below back , my component "plex assistant" is throwing an error on this link -play media player

not sure what component is giving the issue? seems plex is looking for somekind of incompatible media_player

```
media_player:
    - platform: linkplay
      host: !secret arylica50
      name: Luidspeker_Buiten
      volume_step: 5
      sources: 
        {}   
```

```
2021-08-26 13:44:17 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Synology for plex_assistant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/plex_assistant/__init__.py", line 79, in async_setup_entry
    pa = await hass.async_add_executor_job(pa_executor, server, list(start_script.keys()))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 75, in pa_executor
    get_devices(hass, _pa)
  File "/config/custom_components/plex_assistant/helpers.py", line 50, in get_devices
    for entity in list(hass.data["media_player"].entities):
KeyError: 'media_player'
```

**Comment by nagyrobi** [comment]
The error is generated by plex assistant, specifically by the line 50 in `custom_components/plex_assistant/helpers.py`.

You should contact them with this error.
